// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDuZSP8dlN6_sN6ZCPraz5NnmiowPSDYmM",
      authDomain: "ezypos-c26f4.firebaseapp.com",
      databaseURL: "https://ezypos-c26f4-default-rtdb.firebaseio.com",
      projectId: "ezypos-c26f4",
      storageBucket: "ezypos-c26f4.firebasestorage.app",
      messagingSenderId: "830746184414",
      appId: "1:830746184414:web:90427c5b2c2a0bedb3904f"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyC6ZbV0uRISITcc5FHQvh97-1pEkMVACO8',
      appId: '1:830746184414:android:1f0d8c74b62c1c76b3904f',
      messagingSenderId: '830746184414',
      projectId: 'ezypos-c26f4',
      storageBucket: 'ezypos-c26f4.firebasestorage.app',
      databaseURL: 'https://ezypos-c26f4-default-rtdb.firebaseio.com');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKDgHRWPDdlWarcWizDf4ZsP55jRm-SY',
    appId: '1:77048286492:ios:22cb6c02e5c1c83c847ed9',
    messagingSenderId: '77048286492',
    projectId: 'salespro-saas-4a6d5',
    storageBucket: 'salespro-saas-4a6d5.appspot.com',
    databaseURL: 'https://salespro-saas-4a6d5-default-rtdb.firebaseio.com',
    iosClientId: '77048286492-argcr9ue3lj2avu6qhheek5r57r0u3so.apps.googleusercontent.com',
    iosBundleId: 'com.maantheme.mobilepos',
  );
}
